run:
  skip-dirs-use-default: true

linters:
  enable:
    - goimports
    - gofmt
    - misspell
    - gosec
    - maligned
    - unconvert
    - golint
    - gocognit
    - gocyclo
    - gocritic
  fast: true

linters-settings:
  misspell:
    locale: US
  golint:
    min-confidence: 0
  govet:
    check-shadowing: false
  goimports:
    local-prefixes: github.com/SVilgelm/bumptag
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true



issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
