language: go


branches:
  only:
    - master
    - /^(v)?\d+\.\d+\.\d+(-.*)?$/


stages:
  - style
  - deploy


jobs:
  include:
    - stage: style
      name: "gofmt"
      script: diff -u <(echo -n) <(gofmt -d -s .)
    - name: "golint"
      install: go get -u golang.org/x/lint/golint
      script: golint -set_exit_status ./...
    - name: "govet"
      script: go vet ./...
    - stage: deploy
      name: "Update goreportcard"
      script: curl --fail --request POST "https://goreportcard.com/checks" --data "repo=github.com/SVilgelm/bumpversion"
      if: branch = master AND type = push
    - stage: deploy
      name: "Upload binaries"
      if: tag IS present AND type = push
      script:
        - mkdir .build
        - GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${TRAVIS_TAG}" -o ".build/bumpversion-${TRAVIS_TAG}-linux-amd64"
        - gzip ".build/bumpversion-${TRAVIS_TAG}-linux-amd64"
        - GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${TRAVIS_TAG}" -o ".build/bumpversion-${TRAVIS_TAG}-darwin-amd64"
        - gzip ".build/bumpversion-${TRAVIS_TAG}-darwin-amd64"
        - ls -alh .build/
      deploy:
        provider: releases
        api_key: ${GITHUB_TOKEN}
        on:
          tags: true
        skip_cleanup: true
        file_glob: true
        file: .build/*
