language: go

go:
  - 1.12.x


branches:
  only:
    - master
    - /^v\d+(\.\d+\.\d+-.*)?$/


stages:
  - name: style
    if: type == pull_request
  - name: test
  - name: deploy
    if: type == push


jobs:
  include:
    - stage: style
      name: "Style check"
      script: make stylecheck
    - stage: test
      name: "Unit tests"
      IF: tag IS NOT present
      script: make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      name: "Update goreportcard"
      script: curl --fail --request POST "https://goreportcard.com/checks" --data "repo=github.com/SVilgelm/bumpversion"
      if: branch = master
    - stage: deploy
      name: "Upload binaries"
      if: tag IS present
      before_install:
        - openssl aes-256-cbc -K $encrypted_9c019c2a7526_key -iv $encrypted_9c019c2a7526_iv -in .extra/build/bumpversion.gpg.enc -out bumpversion.gpg -d
        - gpg --import bumpversion.gpg
      script:
        - make build-all
      deploy:
        provider: releases
        api_key: ${GITHUB_TOKEN}
        on:
          tags: true
        skip_cleanup: true
        file_glob: true
        file: .build/*
